### ISSUE TITLE
[BUG] fixKeys for senderProfile errors on deploy

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#1299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/Accenture/sfmc-devtools/assets/1917227/d6e281de-8759-4041-ae2f-e0a313a88ee5)

12:32:40.155 info: Found 12 senderProfile keys to fix
12:32:40.158 info: mcdev:: Deploy
12:32:40.168 info: :: Deploying to R1/Randstad_X2GCQA2
12:32:40.182 warn: No deployable metadata found for type senderProfile for selected keys
12:32:40.184 error: No metadata found in deploy folder for selected BU
12:32:40.184 debug: Util.signalFataError() sets process.exitCode = 1 unless already set
12:32:40.185 info: :: Deployed 1 BUs

12:32:40.185 error: mcdev.fixKeys failed:
12:32:40.187 error:     Cannot convert undefined or null to object (undefined)
12:32:40.187 debug: Util.signalFataError() sets process.exitCode = 1 unless already set
12:32:40.188 debug: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at #fixKeys (file:///C:/Git/sfmc-devtools/lib/index.js:1224:52)
    at async #runOnBU (file:///C:/Git/sfmc-devtools/lib/index.js:1092:44)
    at async #runMethod (file:///C:/Git/sfmc-devtools/lib/index.js:1044:46)
12:32:40.189 info: :: Done

![image](https://github.com/Accenture/sfmc-devtools/assets/1917227/8a1db8c1-8e72-4daa-a18f-a58a4086532e)

### Expected Behavior

should find the files in the retrieve folder

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

6.0.2

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
Duplicate of #1298
