### ISSUE TITLE
[BUG] FuelSoap Exception when retrieving Folder data type

### ISSUE THREAD

**Issue by asilva102** [Accenture/sfmc-devtools#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to retrieve the metadatatype "Folder" a FuelSoap from a certain business unit an exception is thrown. This only happens for one specific business unit while the all the other business units in the same Installed Package don't have this issue and are able to retrieve the folders list properly.

`TypeError: Cannot read property 'soap:Body' of undefined
    at FuelSoap.<anonymous> (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\fuel-soap\lib\fuel-soap.js:565:38)
    at Parser.<anonymous> (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\xml2js\lib\parser.js:306:18)
    at Parser.emit (events.js:400:28)
    at SAXParser.onclosetag (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\xml2js\lib\parser.js:264:26)
    at emit (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\sax\lib\sax.js:1436:13)
    at Parser.parseString (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\xml2js\lib\parser.js:5:59)
    at FuelSoap._parseResponse (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\fuel-soap\lib\fuel-soap.js:557:2)
    at FuelSoap.<anonymous> (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\fuel-soap\lib\fuel-soap.js:123:9)
    at Request.self.callback (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Parser instance at:
    at Parser.exports.Parser.Parser.parseString (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\xml2js\lib\parser.js:329:16)
    at Parser.parseString (C:\Users\ana.i.silva\Desktop\sfmc_devtools\sfmc-devtools\node_modules\xml2js\lib\parser.js:5:59)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:21)`

### Expected Behavior

Retrieve the list of folders

### Version

3.0.3 (Default)

### Environment

- OS: Windows 10
- Node:  v14.18.1
- npm: 8.3.0

**Comment by DougMidgley** [comment]
Hey @asilva102  do you have the actual results and can you make the same request using the normal SOAP api?

**Comment by asilva102** [comment]
Hi @DougMidgley . I tried doing a SOAP request to this same business unit on POSTMAN and I get an error message from the api. Used the same soap body for another business unit and it worked fine.

Here is the error message:
![folder_retrieve_error_postman](https://user-images.githubusercontent.com/66126240/147950290-42f5aa04-a934-4d24-a586-aa4089203a34.PNG)

**Comment by DougMidgley** [comment]
Looks like a Salesforce error, best to open a support ticket:)
