### ISSUE TITLE
[BUG] deploying template and template-based email in one go ends with "does not have field 'id'"

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#1772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the api does return the id for the template but it does not seem to make its way into the cache for some reason

error:  ☇ skipping asset email_key / email_name: asset with customerKey 'templatekey' does not have field 'id'

    at Object.searchForField (file:///C:/Git/sfmc-devtools/lib/util/cache.js:145:27)
    at Asset.preDeployTasks (file:///C:/Git/sfmc-devtools/lib/metadataTypes/Asset.js:808:53)
    at Asset.upsert (file:///C:/Git/sfmc-devtools/lib/metadataTypes/MetadataType.js:734:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Asset.deploy (file:///C:/Git/sfmc-devtools/lib/metadataTypes/MetadataType.js:137:37)
    at async Deployer._deploy (file:///C:/Git/sfmc-devtools/lib/Deployer.js:363:32)
    at async Deployer._deployBU (file:///C:/Git/sfmc-devtools/lib/Deployer.js:248:40)
    at async Deployer.deploy (file:///C:/Git/sfmc-devtools/lib/Deployer.js:204:46)
    at async Mcdev.deploy (file:///C:/Git/sfmc-devtools/lib/index.js:503:30)

looks like this type-interdependency is not resolved for some reason

### Version

7.4.3

**Comment by JoernBerkefeld** [comment]
confirmed fixed
- #2076
