### ISSUE TITLE
[BUG] ECONNRESET not caught by SDK?

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/1917227/160275213-59be4e04-0907-4869-8a9a-8fcf9e7fefb3.png)

and as text:
11:19:02.609 debug: :: mcdev 3.1.3 ::
11:19:05.461 info: mcdev:: Deploy
11:19:05.550 info: ::Deploying ACN-Learning/MCDEV_Training_Target_2
11:19:05.575 warn: _createFolderDefinitions(emailSendDefinition: userinitiatedsends) - folderType not supported for deployment
11:19:05.592 info: Caching dependent Metadata: folder
11:19:08.295 info: Caching dependent Metadata: email
11:19:08.297 warn: Classic E-Mails are deprecated and will be discontinued by SFMC in the near future. Ensure that you migrate any existing E-Mails to Content Builder as soon as possible.
11:19:09.035 info: Caching dependent Metadata: asset-message
11:19:09.069 info: - Caching Subtype: message
11:19:10.015 info: Caching dependent Metadata: dataExtension
11:19:11.183 info: - Caching dependent Metadata: dataExtension (shared via _ParentBU_)
11:19:15.953 info: - Caching dependent Metadata: folder (shared via _ParentBU_)
11:20:44.799 error: mcdev.deploy failed: read ECONNRESET
11:20:44.799 debug: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
11:20:44.800 info: 
:: Deployed 1 BUs

### Expected Behavior

auto-retry executed by SDK

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

3.1.3

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
ERROR (soap._apiRequest) Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'text/xml',
      SOAPAction: 'Retrieve',
      'User-Agent': 'axios/0.26.0',
      'Content-Length': 1345
    },
    method: 'post',
    baseURL: 'https://mct0l7nxfq2r988t1kxfy8sc47mq.soap.marketingcloudapis.com/',
    url: '/Service.asmx',
    data: '<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Body><RetrieveRequestMsg xmlns="http://exacttarget.com/wsdl/partnerAPI"><RetrieveRequest><ObjectType>DataFolder</ObjectType><Properties>ID</Properties><Properties>Client.ID</Properties><Properties>CustomerKey</Properties><Properties>Description</Properties><Properties>CreatedDate</Properties><Properties>ModifiedDate</Properties><Properties>ContentType</Properties><Properties>IsActive</Properties><Properties>IsEditable</Properties><Properties>AllowChildren</Properties><Properties>Name</Properties><Properties>ParentFolder.CustomerKey</Properties><Properties>ParentFolder.ID</Properties></RetrieveRequest></RetrieveRequestMsg></Body><Header><fueloauth xmlns="http://exacttarget.com">eyJhbGciOiJIUzI1NiIsImtpZCI6IjQiLCJ2ZXIiOiIxIiwidHlwIjoiSldUIn0.eyJhY2Nlc3NfdG9rZW4iOiI3NllxRjZEWGFHU2xYeERyVTRtdkJrRDIiLCJjbGllbnRfaWQiOiIwbTBoZXQ2bXFrbnp2MHVlYnFsdm9vNDEiLCJlaWQiOjcyODE2OTgsInN0YWNrX2tleSI6IlM3IiwicGxhdGZvcm1fdmVyc2lvbiI6MiwiY2xpZW50X3R5cGUiOiJTZXJ2ZXJUb1NlcnZlciJ9.uki4DcK9Zvv8dP3TFreFH6e_r35k7wcBjXq6ZGIhSfY.Ou-mAffRix4alZ6JcpPjWZD6XC-6Ju-1Elx9o1EGFEjrJFR2Fpna6jZNTH8TDxRZtJNrLBmVoRP_8O-bVOjNE4FVnU0_bEL2H3L4bNlwogJHI--9m-cvVoJAdiaqP5ZOgDj-vnHHGkdRdAynnDU6j07sUzD4D3iZJUfK_vUcTODbquugceOQgAm</fueloauth></Header></Envelope>'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/Service.asmx',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'mct0l7nxfq2r988t1kxfy8sc47mq.soap.marketingcloudapis.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/Service.asmx'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 1345,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /Service.asmx HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: text/xml\r\n' +
        'SOAPAction: Retrieve\r\n' +
        'User-Agent: axios/0.26.0\r\n' +
        'Content-Length: 1345\r\n' +
        'Host: mct0l7nxfq2r988t1kxfy8sc47mq.soap.marketingcloudapis.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/Service.asmx',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'mct0l7nxfq2r988t1kxfy8sc47mq.soap.marketingcloudapis.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://mct0l7nxfq2r988t1kxfy8sc47mq.soap.marketingcloudapis.com/Service.asmx',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
