### ISSUE TITLE
[BUG] ECONNRESET during retrieving campaign not handled

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#46]
**Describe the bug**
ECONNRESET during retrieving campaign not handled:

11:58:26 info: Retrieving: campaign
(node:27896) UnhandledPromiseRejectionWarning: Error: Error: read ECONNRESET
    at C:\Users\joern.berkefeld\AppData\Roaming\npm\node_modules\mcdev\lib\metadataTypes\Campaign.js:25:27
    at Campaign.<anonymous> (C:\Users\joern.berkefeld\AppData\Roaming\npm\node_modules\mcdev\node_modules\sfmc-fuelsdk-node\lib\objects\Campaign.js:53:4)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**To Reproduce**
1. start retrieving campaigns
2. cut your network connection in between
3. See error

**Expected behavior**
It should keep retrying

**Screenshots**
![image](https://user-images.githubusercontent.com/1917227/127305728-5fdbc095-51af-4bd2-9410-4cefaa64ae74.png)

**Versions:**
- mcdev (mcdev --version): 3.1.0
- npm (npm --version): 7.8.0
- node (node --version): 14.16.0
- Operating system (Windows/Mac): win10

**Comment by JoernBerkefeld** [comment]
done by replacing logic with new SDK code
